#!/system/bin/sh
# Place to /system/etc/init.d/

# Set cpu clocks
echo 62 > /proc/overclock/max_vsel
echo 4 1200000000 62 > /proc/overclock/mpu_opps
echo 3 900000000 47 > /proc/overclock/mpu_opps
echo 2 600000000 32 > /proc/overclock/mpu_opps
echo 1 300000000 22 > /proc/overclock/mpu_opps
echo 0 1200000 > /proc/overclock/freq_table
echo 1 900000 > /proc/overclock/freq_table
echo 2 600000 > /proc/overclock/freq_table
echo 3 300000 > /proc/overclock/freq_table
echo 1200000 > /proc/overclock/max_rate
echo 300000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

# Set gpu clock
echo 266666666 > /proc/gpu/max_rate

# Set noop scheduler for NAND and SDCARD
echo noop > /sys/block/mmcblk0/queue/scheduler
echo noop > /sys/block/mmcblk1/queue/scheduler

# Set governor
echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

# Tune lowmemorykiller (6/8/16/40/50/60)
echo "1536,2048,4096,10240,12800,15360" > /sys/module/lowmemorykiller/parameters/minfree

# Enable KSM
#echo 1 > /sys/kernel/mm/ksm/run

# Enable zRAM (128 Mb)
#echo 134217728 > /sys/block/zram0/disksize
#mkswap /dev/block/zram0
#swapon /dev/block/zram0


