#!/bin/sh
# Evgeny Zobnin (zobnin@gmail.com)

case $1 in
"connect")
    killall adb
    adb connect $2:5555
    ;;
"auto-connect")
    NETWORK=`ifconfig wlan0 | grep netmask | cut -d ' ' -f 10 | cut -d . -f 1-3`
    ADDR=`nmap --open ${NETWORK}.1-255 -p 5555 | grep "report for" | cut -d ' ' -f 5`
    test $ADDR || echo "[EE] No ADB devices in the network" && exit
    killall adb
    for $addr in $ADDR; do
	adb connect $addr
	# TODO: connect to more addresess
	exit
    done
    ;;
"open")
    # TODO проверка на подключение 
    # TODO проверка на http
    adb shell am start -a android.intent.action.VIEW -d $2
    ;;
"text")
    adb shell input text $2
    ;;
"screencap")
    # TODO проверка на подключение 
    adb shell screencap /sdcard/$2
    adb pull /sdcard/$2
    adb shell rm /sdcard/$2
    ;;
"recovery")
    # TODO проверка на подключение 
    adb reboot recovery
    ;;
"shell")
    # TODO: передача параметров
    adb shell
    ;;
"install")
    adb install $2
    ;;
"power")
    adb shell input keyevent 26
    ;;
"killall")
    adb shell am kill-all
    ;;
"softreboot")
    # FIXME
    ;;
"pushall")
    for f in *.$2; do
	adb push $f $3
    done
    ;;
"remount")
    adb shell 'mount -o remount,rw /system'
    ;;
"help")
    echo "aa connect IP     - connect to IP"
    echo "   auto-connect   - connect to near device"
    echo "   open URL       - open URL in browser"
    echo "   text TEXT      - put text in input field"
    echo "   screencap FILE - get screen capture"
    echo "   recovery       - reboot into recovery"
    echo "   shell          - open shell"
    echo "   install FILE   - install apk on device"
    echo "   power          - press power button"
    echo "   kill-all       - kill all background processes"
    echo "   soft-reboot    - perform soft reboot"
    echo "   remount        - remount /system in rw"
    ;;
*)
    adb devices
    ;;
esac

