#!/bin/sh
# Evgeny Zobnin (zobnin@gmail.com)

ADB=`which adb`

case $1 in
"connect")
    adb connect $2
    ;;
"find")
    NETWORK=`ifconfig wlan0 | grep netmask | cut -d ' ' -f 10 | cut -d . -f 1-3`
    ADDR=`nmap --open ${NETWORK}.1-255 -p 5555 | grep "report for" | cut -d ' ' -f 5`
    for addr in $ADDR; do
	$ADB connect $addr
    done
    $ADB devices
    ;;
"view")
    $ADB shell am start -a android.intent.action.VIEW -d $2
    ;;
"text")
    $ADB shell input text $2
    ;;
"screencap")
    $ADB shell screencap /sdcard/$2
    $ADB pull /sdcard/$2
    $ADB shell rm /sdcard/$2
    ;;
"recovery")
    $ADB reboot recovery
    ;;
"shell")
    $ADB shell
    ;;
"install")
    $ADB install $2
    ;;
"power")
    $ADB shell input keyevent 26
    ;;
"killall")
    $ADB shell am kill-all
    ;;
"softreboot")
    # FIXME
    ;;
"pushall")
    for f in *.$2; do
	$ADB push $f $3
    done
    ;;
"remount")
    adb shell 'mount -o remount,rw /system'
    ;;
"help")
    echo "aa connect IP     - connect to IP"
    echo "   find           - connect to near device"
    echo "   view URL       - open URL in browser"
    echo "   text TEXT      - put text in input field"
    echo "   screencap FILE - get screen capture"
    echo "   recovery       - reboot into recovery"
    echo "   shell          - open shell"
    echo "   install FILE   - install apk on device"
    echo "   power          - press power button"
    echo "   kill-all       - kill all background processes"
    echo "   soft-reboot    - perform soft reboot"
    echo "   remount        - remount /system in rw"
    ;;
*)
    adb devices
    ;;
esac

